# Generated by Django 3.2.15 on 2022-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceHistoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
